# take pateela

FROM python:3.13

# Add ingredients
  
WORKDIR /app

COPY . .

# mix / process the item

RUN pip install -r requirements.txt 

EXPOSE 8000
# gas on 

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
